GOOSE_DRIVER ?= postgres
GOOSE_MIGRATION_DIR ?= migrations

up:
	@GOOSE_DRIVER=$(GOOSE_DRIVER) GOOSE_DBSTRING=$(GOOSE_DBSTRING) goose -v -dir=$(GOOSE_MIGRATION_DIR) up

up-to:
	@GOOSE_DRIVER=$(GOOSE_DRIVER) GOOSE_DBSTRING=$(GOOSE_DBSTRING) goose -v -dir=$(GOOSE_MIGRATION_DIR) up-to $(version)

down:
	@GOOSE_DRIVER=$(GOOSE_DRIVER) GOOSE_DBSTRING=$(GOOSE_DBSTRING) goose -v -dir=$(GOOSE_MIGRATION_DIR) down

down-to:
	@GOOSE_DRIVER=$(GOOSE_DRIVER) GOOSE_DBSTRING=$(GOOSE_DBSTRING) goose -v -dir=$(GOOSE_MIGRATION_DIR) down-to $(version)

reset:
	@GOOSE_DRIVER=$(GOOSE_DRIVER) GOOSE_DBSTRING=$(GOOSE_DBSTRING) goose -v -dir=$(GOOSE_MIGRATION_DIR) reset

.PHONY: up up-to down down-to reset