apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-authentication-ingress
  annotations:
    konghq.com/strip-path: "true"
    konghq.com/plugins: "rate-limiting"
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: go-authentication
                port:
                  number: 80
