apiVersion: v1
kind: Secret
metadata:
  name: go-auth-secrets
type: Opaque
data:
  # IMPORTANT: DO NOT FILL THESE VALUES IN VERSION CONTROL
  # These are placeholders - replace at deployment time with actual values
  # Example command to create secret manually:
  # kubectl create secret generic go-auth-secrets \
  #   --from-literal=DB_USER=your-db-user \
  #   --from-literal=DB_PASSWORD=your-db-password \
  #   --from-literal=JWT_SECRET=your-jwt-secret \
  #   -n auth-system

  # Placeholders only - DO NOT USE THESE VALUES
  DB_USER: REPLACE_AT_DEPLOYMENT_TIME
  DB_PASSWORD: REPLACE_AT_DEPLOYMENT_TIME
  JWT_SECRET: REPLACE_AT_DEPLOYMENT_TIME
